### ISSUE TITLE
Install fails on TS-453A

### ISSUE THREAD

**Issue by jenswegar** [JaredReisinger/docker-qpkg#1]
First off, thanks for the work on this so far and for sharing it to the world! I got the sad message from Qnap support that they currently have no plans to update the Docker engine in their Container station, which is why I'm very happy to have found this repo. 

I've been trying to get this package to run on my TS-453A, but it fails with a message to check the system logs when I do the manual installation. But when I check the logs, I don't see any lines that would tell me what went wrong.

I built the qpkg by cloning this Git repo to my qnap, then running "make" through a terminal session on the qnap directly. It seems to have built everything ok, at least I saw no complaints in the output (complete output below). But the install still fails...

Any ideas as to what might be going wrong, or where I should start looking? I'm very new to the whole custom qpkg world, so I don't really even have any idea of where to start debugging. 

```
[/share/GitRepos/docker-qpkg] # make                                                                                                                  
mkdir -p ./_build/data/bin
cp -R ./_build/dist/docker-17.05.0-ce/* ./_build/data/bin
rm -rf ./_build/data/bin/completion
tar -czvf _build/data.tgz -C ./_build/data .
./
./bin/
./bin/docker
./bin/docker-containerd
./bin/docker-containerd-ctr
./bin/docker-containerd-shim
./bin/dockerd
./bin/docker-init
./bin/docker-proxy
./bin/docker-runc
./docker.sh
./.qpkg_icon.gif
./.qpkg_icon_gray.gif
./.qpkg_icon_80.gif
./process-bootstrap -b ./bootstrap.sh -c ./_build/control.tgz -d ./_build/data.tgz -o ./_build/bootstrap.sh
re-wrote output... length changed from 1260 to 1223.
Done!
cat ./_build/bootstrap.sh ./_build/control.tgz ./_build/data.tgz ./_build/tail.txt > _build/Docker_17.05.0-ce.qpkg
```

**Comment by JaredReisinger** [comment]
Hi!

Thanks for reaching out; I'm sad to say that I gave up on getting Docker to work on my QNAP and instead resurrected an old PC as a Linux box on which to run Docker.  If I recall correctly, what I discovered was that the busybox OS build on the QNAP was incomplete/old and simply would not support the networking requirements of Docker, specifically, the stuff needed to create the inter-container network.  The only solution I could imagine was to install a new/custom busybox OS, and I was unwilling to go to that extreme on my main storage device!

I happened to have an old PC I built several years previously--coincidentally as a Windows Home Server, my data storage before I got the QNAP--and it was more than capable of running Linux and hosting Docker.  I'm actually running a slew of containers 24x7 on that machine, and I'm very glad I decided to just go with a "clean" machine, rather than trying to force the QNAP into something it didn't want to do, even if one of the reasons I got *that* QNAP was because of the Intel processors and the expectation that I *could* run Docker, etc.  C'est la vie!

**Comment by jenswegar** [comment]
ok, sorry to hear it didn't work out, but yeah no point in trying to bend the system into doing what it doesn't want to do in this case. Based on this I think I'll also go for setting up a separate box for the containers I want to run, and just map storage to the qnap somehow. Thanks anyway!
